//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

// Any class that implements this interface can position a piece of text as it floats across the screen based on the criteria you give it.

public interface IFloatingTextPositioner
{
	bool GetPosition(ref Vector2 position, GUIContent content, Vector2 size);
}


